### ISSUE TITLE
Duplication of keda resource leads to undefined behaviour

### ISSUE THREAD

**Issue by k15r** [kyma-project/keda-manager#160]
**Description**

- enable keda module
- create a second keda resource => will be almost immediately ready
- delete duplicate of keda resource

**Expected result**
second keda resource should never be ready
resources created by the first keda resource should not be modified by any action taken towards the second keda resource
 

**Actual result**

- first keda resource will still be ready 
- deletion of 2nd keda resource kills the actual keda installation. no `keda operator` nor `keda metrics server` is available after deletion of the 2nd keda-cr

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
When running with LM we end up with Kyma CR stuck in Prgressing and KEda CR w/o any status
```
k get kedas default -n kyma-system -o=jsonpath='{.status}'                                                                                                                                                    
{"state":""}%
```

**Comment by kwiatekus** [comment]
```
git checkout d8bcfdf5f4e9fd6075b789672177c6056e9dd3fd   
make -C hack/local run-with-lifecycle-manager
```
works
