### ISSUE TITLE
Provide detailed message about reason of stuck module deletion 

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/keda-manager#161]
**Description**

When module deletion stuck due to existing scaled objects, it should be properly displayed in module status. Currently displayed message for Keda that stuck in deleting state is misleading (message is from previous state - ready):

> status:
  conditions:
    - lastTransitionTime: '2023-05-16T12:28:07Z'
      message: keda-operator and keda-operator-metrics-server ready
      reason: Verified
      status: 'True'
      type: Installed
  state: Deleting

It should be similar to the way BTP Operator does:

> status:
  conditions:
    - lastTransitionTime: '2023-05-18T08:07:14Z'
      message: >-
        All service instances and bindings must be removed: 1 instance(s) and 0
        binding(s)
      reason: ServiceInstancesAndBindingsNotCleaned
      status: 'False'
      type: Ready
  state: Deleting

**Comment by kwiatekus** [comment]
Initially it was visible in the condition
Currently it is visible in the event (not in the condition).
When we will provide a view for Keda CR those events would be more prominent to the user as only filtered events about the given CR would be shown on the detail view

![Screenshot 2023-05-18 at 13 11 21](https://github.com/kyma-project/keda-manager/assets/6783567/13401e2d-ef98-4072-a8df-58b6a19e90ea)
