### ISSUE TITLE
Align the Prometheus scaler example diagram to the guidelines

### ISSUE THREAD

**Issue by grego952** [kyma-project/keda-manager#336]
**Description**
The Prometheus scaler example diagram in the Scale to Zero With Keda doc must be in line with our guidelines.

**Area**
* Keda Manager
* Documentation

**Reasons**
The diagram is not in line with the guidelines.

**Assignees**
@grego952 

**Attachments**

**Comment by kwiatekus** [comment]
Please also move the prom scaler example to examples folder on root
