### ISSUE TITLE
Automatically bump version in resource labels during release

### ISSUE THREAD

**Issue by halamix2** [kyma-project/keda-manager#453]
**Description**

Automatically bump version stored in chart during release process
The mechanism could be similar to the one used in serverless - version is set to `main` on main branch, and replaced by Github Action with correct version on release.

Currently version would need to be updated in these places:
- [x] docker-registry - mix of config/operator/base/kustomization.yaml and chart
- [x] serverless - mix of kustomize and chart
- [x] keda-manager - config/default/kustomization.yaml (blocked by https://github.com/kyma-project/keda-manager/issues/457)
- [x] warden - charts/warden/Chart.yaml

**Reasons**

After labels update it became necessary to store version in the k8s resources labels.
Currently this version needs to be manually bumped, which can lead to desynchronization and errors

**Attachments**

- https://github.com/kyma-project/serverless/issues/1014

**Comment by kwiatekus** [comment]
I have installed 0.2.0 version of docker registry module on k3d. It ws released last week.
When I lookup for the `app.kubernetes.io/version` label I get nothing back
`k get pods -n kyma-system -oyaml | grep app.kubernetes.io/version`

**Comment by kwiatekus** [comment]
IMO this still doesnt work.
Check the latest 1.4.0 keda release. Download the keda-manager.yaml and check the resource version labels
