### ISSUE TITLE
Smoke Integration Test for Keda module

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#74]
**Description**

Implement a minimal integration test that allows to verify if the keda module is working fine, i.e
 - deploy a ScaledObject CR targetting a deployment
 - verify the status of the ScaledObject CR
 - verify if the underlying HPA is created and has a "ready" status 
 - verify deletion without orphan resources (ScaledObject & HPA)

**Ideas**
 - define a dedicated make target that would allow us to make the extra test
 - two options: 
   -  combine `pull-keda-module-build` with the test  in one job
   -  **run the test in a dependant job (after `pull-keda-module-build` is finished)  - preferred as it goes into worflows in the CI**
 
 
**Reasons**
We as keda module providers we'd need to have an automated way to judge if a keda module version is ready for submission into a target channel.

**Attachments**

**Comment by m00g3n** [comment]
blocked by https://github.com/kyma-project/test-infra/issues/6728
