### ISSUE TITLE
Keda module Upgradability test

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/keda-manager#83]
**Description**

Design and implement integration test that will check if upgrade between two `keda-manager` versions is possible.

The solution can be used to test:
- two versions of module coming from the same channel  
- the promotion of module version from one channel to another

**Reasons**

- Compliance with Operational Test Management

Depends on:
- https://github.com/kyma-project/keda-manager/issues/74

**Ideas**

One step of upgradability test is to fetch and install "latest version from channel"
How to do it? What is the source of the "latest from channel"

it could be simply HEAD from main in the given channel folder, for example
https://github.com/kyma-project/kyma/blob/main/modules/alpha/moduletemplate-keda.yaml

We will implement three jobs

| Jobs | Upgrade from        | Upgrade to             | Required | Repository |
|------|---------------------|------------------------|----------|------------|
| 1    | PR (Keda)           | Release channel (Kyma) | No       | Keda       |
| 2    | Main (Keda)            |      PR (Keda)      | Yes      | Keda       |
| 3    | PR to channel(Kyma) | Release channel (Kyma) | Yes      | Kyma       |

**Comment by tobiscr** [comment]
You can use this [diagram](https://wiki.one.int.sap/wiki/download/attachments/3114038810/testing_strategy_upgrade.png?api=v2) as example process. Reference implementation by Pandas will be created as part of [this issue](https://github.tools.sap/pandas/backlog/issues/9).

**Comment by m00g3n** [comment]
blocked by https://github.com/kyma-project/test-infra/issues/6728

**Comment by m00g3n** [comment]
waiting until [this issue](https://github.com/kyma-project/lifecycle-manager/pull/351) will be propagated to `kyma-cli`

**Comment by kwiatekus** [comment]
Lets assume that upgrade test upgrades keda from given kyma revision (i.e [main](https://github.com/kyma-project/kyma/blob/main/modules/alpha/moduletemplate-keda.yaml)) onto the target PR module version

**Comment by kwiatekus** [comment]
One step of  upgradability test is to fetch and install "latest version from channel"
How to do it? What is the source of the "latest from channel"

 1) it could be simply HEAD from main in the given channel  folder, for example
 https://github.com/kyma-project/kyma/blob/main/modules/alpha/moduletemplate-keda.yaml
 2) it could be version tagged via a special tag, i.e `keda-alpha`

**Comment by Cortey** [comment]
Waits for : https://github.com/kyma-project/lifecycle-manager/issues/459
