### ISSUE TITLE
Drop keda-namespace ownership

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/keda-manager#88]
**Description**

ATM the `keda-manager` owns `kyma-system` namespace, `kyma-system` is shared between multiple modules. 
The deletion of the `keda-manager`module may trigger the deletion of all `keda-system` content.   

AC:
- `keda-manager` should not own `kyma-system` namespace

**Reasons**

The deletion of the `keda-manager`module may trigger the deletion of all `keda-system` content

**Attachments**
- https://github.com/m00g3n/keda-operator/blob/add-finalizer/config/manager/manager.yaml#L1-L6

**Comment by kwiatekus** [comment]
https://github.com/kyma-project/keda-manager/pull/87
