### ISSUE TITLE
Test the latest Kubernetes API compatibility

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/keda-manager#90]
**Description**

Create pipeline to test the latest Kubernetes API.

Exemplary scenario of the test:
- Create a cluster using the latest published stable Kubernetes cluster version
- Run module smoke tests

**Reasons**

- Compliance with Operational Test Management
[Operational Test Management](https://wiki.one.int.sap/wiki/download/attachments/3114038810/testing_strategy_k8sapi.png)

**Comment by kwiatekus** [comment]
Not relevant for Beta release of keda
